# Generated by Django 6.0.5 on 2026-05-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=20),
        ),
    ]
