# Generated by Django 6.0.5 on 2026-05-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_patient_weight_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
