# Generated by Django 6.0.5 on 2026-05-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_patient_created_at_alter_patient_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='department',
            field=models.CharField(choices=[('general', 'General'), ('cancer', 'Cancer')], default='general', max_length=20),
        ),
    ]
