# Generated by Django 6.0.5 on 2026-05-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_patient_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='department',
        ),
    ]
