# Generated by Django 6.0.5 on 2026-05-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_remove_patient_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
