# Generated by Django 6.0.5 on 2026-05-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_alter_patient_options_remove_patient_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=100)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('on_leave', 'On Leave')], default='available', max_length=20)),
                ('appointment_start', models.TimeField()),
                ('appointment_end', models.TimeField()),
                ('consultation_slots', models.PositiveIntegerField(help_text='Number of slots per day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='patient',
            name='preferred_doctor',
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
