# Generated by Django 6.0.5 on 2026-05-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0010_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorslot',
            name='max_bookings',
            field=models.PositiveIntegerField(default=1, help_text='Max patients allowed in this slot'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('slot', 'patient_phone'), name='unique_slot_per_phone'),
        ),
    ]
