# Generated by Django 6.0.5 on 2026-05-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0013_add_doctorprofile_and_patient_assigned_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
